#! /bin/sh

sxhkd &
picom --experimental-backends &
nitrogen --restore &
~/.config/polybar/launch.sh &

# Monitor
bspc monitor -d terminal web vim code 

# Configuration
bspc config border_width         2
bspc config window_gap          9
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


